/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Alert from './src/components/Alert/Alert.svelte';
import options from './src/components/Alert/options.js';

export {
	options
};
export default Alert;
