/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Avatar from './src/components/Avatar/Avatar.svelte';
import options from './src/components/Avatar/options.js';

export {
	options
};
export default Avatar;
