/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Button from './src/components/Button/Button.svelte';
import options from './src/components/Button/options.js';

export {
	options
};
export default Button;
