/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Card from './src/components/Card/Card.svelte';
import options from './src/components/Card/options.js';

export {
	options
};
export default Card;
