/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Dropdown from './src/components/Dropdown/Dropdown.svelte';
import options from './src/components/Dropdown/options.js';

export {
	options
};
export default Dropdown;
