/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Icon from './src/components/Icon/Icon.svelte';
import options from './src/components/Icon/options.js';

export {
	options
};
export default Icon;
