/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Modal from './src/components/Modal/Modal.svelte';
import modal from './src/components/Modal/modal.js';

export {
	modal
};
export default Modal;
