/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Notification from './src/components/Notification/Notification.svelte';
import notification from './src/components/Notification/notification.js';
import options from './src/components/Notification/options.js';

export {
	notification,
	options
};
export default Notification;
