/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Tag from './src/components/Tag/Tag.svelte';
import options from './src/components/Tag/options.js';

export {
	options
};
export default Tag;
