/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import TextInput from './src/components/TextInput/TextInput.svelte';
import options from './src/components/TextInput/options.js';

export {
	options
};
export default TextInput;
