/*** THIS FILE IS AUTOMATICALLY GENERATED BY /build/generate-exports.js ***/

import Tooltip from './src/components/Tooltip/Tooltip.svelte';
import options from './src/components/Tooltip/options.js';

export {
	options
};
export default Tooltip;
